/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Ruchi Patel
 */
public class Customer_Login extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Login
     */
    public Customer_Login() {
        initComponents();
        setDefaultCloseOperation(Customer_Login.DISPOSE_ON_CLOSE);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        UserName_Textfield = new javax.swing.JTextField();
        Lenno = new javax.swing.JLabel();
        Password_Textfield = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        Reset = new javax.swing.JButton();

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reset.png"))); // NOI18N
        jButton2.setText("Reset");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Login");

        Lname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lname.setText("Username:");

        UserName_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        UserName_Textfield.setForeground(new java.awt.Color(204, 204, 204));
        UserName_Textfield.setText("Enter Username");
        UserName_Textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserName_TextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserName_TextfieldFocusLost(evt);
            }
        });
        UserName_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserName_TextfieldActionPerformed(evt);
            }
        });

        Lenno.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lenno.setText("Password:");

        Password_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Password_Textfield.setForeground(new java.awt.Color(204, 204, 204));
        Password_Textfield.setText("Enter Password");
        Password_Textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_TextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_TextfieldFocusLost(evt);
            }
        });

        Login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset2.png"))); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Lname)
                            .addGap(18, 18, 18)
                            .addComponent(UserName_Textfield)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lenno)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reset)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserName_Textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lenno)
                    .addComponent(Password_Textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserName_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserName_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserName_TextfieldActionPerformed

    private void UserName_TextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserName_TextfieldFocusGained
        // TODO add your handling code here:
        if(UserName_Textfield.getText().equals("Enter Username"))
        {
            UserName_Textfield.setText("");
            UserName_Textfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_UserName_TextfieldFocusGained

    private void UserName_TextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserName_TextfieldFocusLost
        // TODO add your handling code here:
        if(UserName_Textfield.getText().equals(""))
        {
            UserName_Textfield.setText("Enter Username");
            UserName_Textfield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_UserName_TextfieldFocusLost

    private void Password_TextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_TextfieldFocusGained
        // TODO add your handling code here:
         if(Password_Textfield.getText().equals("Enter Password"))
        {
            Password_Textfield.setText("");
            Password_Textfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Password_TextfieldFocusGained

    private void Password_TextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_TextfieldFocusLost
        // TODO add your handling code here:
         if(Password_Textfield.getText().equals(""))
        {
            Password_Textfield.setText("Enter Password");
            Password_Textfield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Password_TextfieldFocusLost

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        username = UserName_Textfield.getText();
        password = Password_Textfield.getText();
        String Error = "";
        int Flag = 0;
        
        if(username.equals("Enter Username"))
        {
            Flag = 1;
            Error += " Username ";
        }
        else
        {
           // Flag = 0;
            Error += "";
        }
        if(password.equals("Enter Password"))
        {
            Flag = 1;
            Error += " Password ";
        }
        else
        {
            //Flag = 0;
            Error += "";
        }
        if(Flag == 1)
        {
            JOptionPane.showMessageDialog(rootPane,Error+"Cannot be Empty");
        }
        else
        {
            try
            {
                Flag = 1;
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery("select * from customer_details");
                
                 while(rs.next())
                {
                    email=rs.getString(2);
                    if(email.equals(username))
                    {
                        Flag=0;
                        name=rs.getString(1);
                        password1=rs.getString(3);
                        if(password1.equals(password))
                        {
                            //JOptionPane.showMessageDialog(rootPane," Login Successful.Welcome "+name);
                            new Customer_Main_Page(name,email).setVisible(true);
                            
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane,"Incorrect Password  for "+email);
                        }
                    }
                }
                if(Flag==1)
                {
                    JOptionPane.showMessageDialog(rootPane," This Mail ID is not registered. Please Register First. ");
                }
                cn.close();
            }
            catch(SQLException s)
            {
                JOptionPane.showMessageDialog(rootPane," This Mail ID is not registered. Please LOGIN. ");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane," Error.");
            }
            UserName_Textfield.setText("Enter Username");
            UserName_Textfield.setForeground(new Color(204,204,204));
            Password_Textfield.setText("Enter Password");
            Password_Textfield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        UserName_Textfield.setText("Enter Username");
        UserName_Textfield.setForeground(new Color(204,204,204));
        Password_Textfield.setText("Enter Password");
        Password_Textfield.setForeground(new Color(204,204,204));
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Customer_Login().setVisible(true);
            }
        });
    }
    
    private String username;
    private String password;
    private String name;
    private String password1;
    private String email;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lenno;
    private javax.swing.JLabel Lname;
    private javax.swing.JButton Login;
    private javax.swing.JTextField Password_Textfield;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField UserName_Textfield;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
