/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Ruchi Patel
 */
public class Cylinder_Infrormation extends javax.swing.JFrame {

    /**
     * Creates new form Cylinder_Infrormation
     */
    public Cylinder_Infrormation(String e) {
         
            initComponents();
            setDefaultCloseOperation(Cylinder_Infrormation.DISPOSE_ON_CLOSE);
            dispose();
            Email=e;
            Email_Textfield.setForeground(new Color(0,0,0));
            Email_Textfield.setText(Email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Lemail = new javax.swing.JLabel();
        Email_Textfield = new javax.swing.JTextField();
        LAvailable_Cylinder = new javax.swing.JLabel();
        Available_Cylinder_Textfield = new javax.swing.JTextField();
        Lcost = new javax.swing.JLabel();
        Cost_Textfield = new javax.swing.JTextField();
        Lstate = new javax.swing.JLabel();
        State_Textfield = new javax.swing.JTextField();
        Laddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Submit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        City_Textfield = new javax.swing.JTextField();
        Lcity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cylinder Details");

        Lemail.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lemail.setText("Email:");

        Email_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Email_Textfield.setForeground(new java.awt.Color(204, 204, 204));
        Email_Textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_TextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_TextfieldFocusLost(evt);
            }
        });
        Email_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_TextfieldActionPerformed(evt);
            }
        });

        LAvailable_Cylinder.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LAvailable_Cylinder.setText("Available Cylinder:");

        Available_Cylinder_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Available_Cylinder_Textfield.setForeground(new java.awt.Color(204, 204, 204));
        Available_Cylinder_Textfield.setText("Enter Available Cylinder");
        Available_Cylinder_Textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Available_Cylinder_TextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Available_Cylinder_TextfieldFocusLost(evt);
            }
        });
        Available_Cylinder_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Available_Cylinder_TextfieldActionPerformed(evt);
            }
        });

        Lcost.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lcost.setText("Cost:");

        Cost_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cost_Textfield.setForeground(new java.awt.Color(204, 204, 204));
        Cost_Textfield.setText("Enter Cost");
        Cost_Textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Cost_TextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Cost_TextfieldFocusLost(evt);
            }
        });
        Cost_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cost_TextfieldActionPerformed(evt);
            }
        });

        Lstate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lstate.setText("State:");

        State_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        State_Textfield.setForeground(new java.awt.Color(204, 204, 204));
        State_Textfield.setText("Enter Your State");
        State_Textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                State_TextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                State_TextfieldFocusLost(evt);
            }
        });
        State_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                State_TextfieldActionPerformed(evt);
            }
        });

        Laddress.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Laddress.setText("Address:");

        jScrollPane1.setToolTipText("dnsjk");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jTextArea1.setText("Enter Address");
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Quantity(In Liters):");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "5", "10", "15", "20" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Submit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add image.png"))); // NOI18N
        Submit.setText("Add Image");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset2.png"))); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        City_Textfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        City_Textfield.setForeground(new java.awt.Color(204, 204, 204));
        City_Textfield.setText("Enter City");
        City_Textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                City_TextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                City_TextfieldFocusLost(evt);
            }
        });
        City_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                City_TextfieldActionPerformed(evt);
            }
        });

        Lcity.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lcity.setText("City:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lemail)
                    .addComponent(jLabel1)
                    .addComponent(LAvailable_Cylinder)
                    .addComponent(Lstate)
                    .addComponent(Laddress)
                    .addComponent(Lcost)
                    .addComponent(Lcity))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Available_Cylinder_Textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(State_Textfield)
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cost_Textfield)
                    .addComponent(Email_Textfield)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(City_Textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lemail)
                    .addComponent(Email_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Available_Cylinder_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LAvailable_Cylinder)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(State_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lstate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(City_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lcity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Laddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cost_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lcost))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Email_TextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_TextfieldFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Email_TextfieldFocusGained

    private void Email_TextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_TextfieldFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Email_TextfieldFocusLost

    private void Email_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_TextfieldActionPerformed

    private void Available_Cylinder_TextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Available_Cylinder_TextfieldFocusGained
        // TODO add your handling code here:
        if(Available_Cylinder_Textfield.getText().equals("Enter Available Cylinder"))
        {
            Available_Cylinder_Textfield.setText("");
            Available_Cylinder_Textfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Available_Cylinder_TextfieldFocusGained

    private void Available_Cylinder_TextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Available_Cylinder_TextfieldFocusLost
        // TODO add your handling code here:
        if(Available_Cylinder_Textfield.getText().equals(""))
        {
            Available_Cylinder_Textfield.setText("Enter Available Cylinder");
            Available_Cylinder_Textfield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Available_Cylinder_TextfieldFocusLost

    private void Available_Cylinder_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Available_Cylinder_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Available_Cylinder_TextfieldActionPerformed

    private void State_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_State_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_State_TextfieldActionPerformed

    private void Cost_TextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Cost_TextfieldFocusGained
        // TODO add your handling code here:
        if(Cost_Textfield.getText().equals("Enter Cost"))
        {
            Cost_Textfield.setText("");
            Cost_Textfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Cost_TextfieldFocusGained

    private void Cost_TextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Cost_TextfieldFocusLost
        // TODO add your handling code here:
         if(Cost_Textfield.getText().equals(""))
        {
            Cost_Textfield.setText("Enter Cost");
            Cost_Textfield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_Cost_TextfieldFocusLost

    private void State_TextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_State_TextfieldFocusGained
        // TODO add your handling code here:
        if(State_Textfield.getText().equals("Enter Your State"))
        {
            State_Textfield.setText("");
            State_Textfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_State_TextfieldFocusGained

    private void jTextArea1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusGained
        // TODO add your handling code here:
        if(jTextArea1.getText().equals("Enter Address"))
        {
            jTextArea1.setText("");
            jTextArea1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextArea1FocusGained

    private void State_TextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_State_TextfieldFocusLost
        // TODO add your handling code here:
        if(State_Textfield.getText().equals(""))
        {
            State_Textfield.setText("Enter Your State");
            State_Textfield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_State_TextfieldFocusLost

    private void jTextArea1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusLost
        // TODO add your handling code here:
        if(jTextArea1.getText().equals(""))
        {
            jTextArea1.setText("Enter Address");
            jTextArea1.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jTextArea1FocusLost

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        Available_Cylinder = Available_Cylinder_Textfield.getText();
        Q = (String)jComboBox1.getSelectedItem();
        State = State_Textfield.getText();
        Address = jTextArea1.getText();
        C = Cost_Textfield.getText();
        City = City_Textfield.getText();
        String Error = "";
        int Flag = 0;
        int Flag2 = 0;
        ;
        
        if(Available_Cylinder.equals("Enter Available Cylinder"))
        {
            Flag = 1;
            Error += " Available Cylinder ";
        }
        else
        {
            Error += "";
        }
        if(Q.isEmpty())
        {
            Flag = 1;
            Error += " Quantity ";
        }
        else
        {
            Error += "";  
            Quantity = Integer.parseInt(Q);
        }
        for(int i=0;i<k;i++)
        {
            if(Arrived[i] == Quantity)
            {
                Flag2 = 1;
                break;
            }
        }
        if(Flag2 == 0)
        {
            Arrived[k] = Quantity;
            k++;
        }
        if(State.equals("Enter State"))
        {
            Flag = 1;
            Error += "State";
        }
        else
        {
            Error += "";
        }
        if(City.equals("Enter City"))
        {
            Error += " City ";
            Flag = 1;
        }
        else
        {
            Error += "";
            //Flag1 = 0;
        }
        if(Address.equals("Enter Address"))
        {
            Flag = 1;
            Error += "Address";
        }
        else
        {
            Error += "";
        }
        if(C.equals("Enter Cost"))
        {
            Flag = 1;
            Error += "Cost";
        }
        else
        {
            Error += "";
            Cost = Integer.parseInt(C);
        }
        if(Flag == 1)
        {
            JOptionPane.showMessageDialog(rootPane, Error+"Cannot be Empty");
        }
        else if(Flag2 == 1)
        {
            JOptionPane.showMessageDialog(rootPane, " Already Added this Quantity...Please change the Quantity ");
        }
        else
        {
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
                Statement st = cn.createStatement();
                
                int i = st.executeUpdate("insert into cylinder_information values('"+Email+"','"+Quantity+"','"+Available_Cylinder+"','"+State+"','"+City+"','"+Address+"','"+Cost+"')");
                
                if(i == 1)
                {
                    JOptionPane.showMessageDialog(rootPane," Submitted Successfully ");
                    //setDefaultCloseOperation(Cylinder_Infrormation.DISPOSE_ON_CLOSE);
                    //dispose();
                    Add_Cylinder_Image o1 = new Add_Cylinder_Image(Email,Quantity);
                    o1.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane," Error in Submitting .... ");
                }
                cn.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane," Error in Registering DB ...."+e);
            }
            Available_Cylinder_Textfield.setText("Enter Available Cylinder");
            Available_Cylinder_Textfield.setForeground(new Color(204,204,204));
            jComboBox1.setSelectedIndex(0);
            State_Textfield.setText("Enter Your State");
            State_Textfield.setForeground(new Color(204,204,204));
            jTextArea1.setText("Enter Address");
            jTextArea1.setForeground(new Color(204,204,204));
            Cost_Textfield.setText("Enter Cost");
            Cost_Textfield.setForeground(new Color(204,204,204));
        }    
    }//GEN-LAST:event_SubmitActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Available_Cylinder_Textfield.setText("Enter Available Cylinder");
        Available_Cylinder_Textfield.setForeground(new Color(204,204,204));
        jComboBox1.setSelectedIndex(0);
        State_Textfield.setText("Enter Your State");
        State_Textfield.setForeground(new Color(204,204,204));
        jTextArea1.setText("Enter Address");
        jTextArea1.setForeground(new Color(204,204,204));
        Cost_Textfield.setText("Enter Cost");
        Cost_Textfield.setForeground(new Color(204,204,204));
        
    }//GEN-LAST:event_ResetActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void City_TextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_City_TextfieldFocusGained
        // TODO add your handling code here:
        if(City_Textfield.getText().equals("Enter City"))
        {
            City_Textfield.setText("");
            City_Textfield.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_City_TextfieldFocusGained

    private void City_TextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_City_TextfieldFocusLost
        // TODO add your handling code here:
        if(City_Textfield.getText().equals(""))
        {
            City_Textfield.setText("Enter City");
            City_Textfield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_City_TextfieldFocusLost

    private void City_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_City_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_City_TextfieldActionPerformed

    private void Cost_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cost_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cost_TextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cylinder_Infrormation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cylinder_Infrormation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cylinder_Infrormation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cylinder_Infrormation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Cylinder_Infrormation().setVisible(true);
            }
        });
    }
    
    private String Email;
    private String Available_Cylinder;
    private String State;
    private String Address;
    private String C;
    private String Q;
    private int Cost;
    private String City;
    private int Quantity;
    int[] Arrived = new int[6];
    int k = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Available_Cylinder_Textfield;
    private javax.swing.JTextField City_Textfield;
    private javax.swing.JTextField Cost_Textfield;
    private javax.swing.JTextField Email_Textfield;
    private javax.swing.JLabel LAvailable_Cylinder;
    private javax.swing.JLabel Laddress;
    private javax.swing.JLabel Lcity;
    private javax.swing.JLabel Lcost;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Lstate;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField State_Textfield;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
