/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruchi Patel
 */
public class View_Ordered_Cylinder extends javax.swing.JFrame {

    /**
     * Creates new form Order_Cylinder
     */
    public View_Ordered_Cylinder(String SE,String CE,int Q,String Oid) 
    {
        initComponents();
        setDefaultCloseOperation(View_Ordered_Cylinder.DISPOSE_ON_CLOSE);
        dispose();
        
        Supplier_Email = SE;
        Customer_Email = CE;
        Quantity = Q;
        Order_id = Oid;
        
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("select * from cylinder_information where Email='"+Supplier_Email+"' and Quantity='"+Quantity+"'");
            
            while(rs.next())
            {
                Supplier_Email = rs.getString(1);
                Quantity = rs.getInt(2);
                No_of_Cylinder = rs.getString(3);
                State = rs.getString(4);
                City = rs.getString(5);
                Address = rs.getString(6);
                Cost = rs.getInt(7);
            }
            
            Lemail.setText(Supplier_Email);
            Lquantity.setText(Integer.toString(Quantity));
            Lnoofcylinders.setText(No_of_Cylinder);
            Lstate.setText(State);
            Lcity.setText(City);
            Laddress.setText(Address);
            Lcost.setText(Integer.toString(Cost));
            
            cn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, " Something Went Wrong1 ...");
        }
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("select * from supplier_details where Email='"+Supplier_Email+"'");
            
            while(rs.next())
            {
                Supplier_Name = rs.getString(1);
                pincode = rs.getString(5);
                Contact_no = rs.getString(6);
            }
            
            Lname.setText(Supplier_Name);
            Lpincode.setText(pincode);
            Lcontact_no.setText(Contact_no);
           
            cn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, " Something Went Wrong2 ...");
        }
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/se_project?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "root");
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("select * from order_cylinder where Supplier_Email='"+Supplier_Email+"' and Order_id='"+Order_id+"' ");
            
            while(rs.next())
            {
                Customer_Address = rs.getString(6);
                Customer_City = rs.getString(7);
                Customer_State = rs.getString(8);
                Ordered_No_of_Cylinder = rs.getInt(9);
                Amount = rs.getInt(10);
            }
            
            Lcustomer_address.setText(Customer_Address);
            Lcustomer_city.setText(Customer_City);
            Lcustomer_State.setText(Customer_State);
            Lordered_cylinder.setText(Integer.toString(Ordered_No_of_Cylinder));
            Lamount.setText(Integer.toString(Amount));
           
            cn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, " Something Went Wrong3 ...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Lemail = new javax.swing.JLabel();
        Lnoofcylinders = new javax.swing.JLabel();
        Lcost = new javax.swing.JLabel();
        Laddress = new javax.swing.JLabel();
        Lcity = new javax.swing.JLabel();
        Lstate = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        Lpincode = new javax.swing.JLabel();
        Lcontact_no = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Lcustomer_address = new javax.swing.JLabel();
        Lcustomer_city = new javax.swing.JLabel();
        Lcustomer_State = new javax.swing.JLabel();
        Lordered_cylinder = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Lamount = new javax.swing.JLabel();
        Lquantity = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Supplier Email:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Quantity(in liters):");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Available Cylinders:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Cost Per Cylinder:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Address:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("City:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("State:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Supplier Name:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Pincode:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Supplier Conatct_No.:");

        Lemail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        Lnoofcylinders.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lnoofcylinders.setText("a");

        Lcost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcost.setText("a");

        Laddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Laddress.setText("a");

        Lcity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcity.setText("a");

        Lstate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lstate.setText("a");

        Lname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lname.setText("a");

        Lpincode.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lpincode.setText("a");

        Lcontact_no.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcontact_no.setText("a");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Customer's Address:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Customer's City:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Customer's State:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Required Cylinders:");

        Lcustomer_address.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_address.setText("a");

        Lcustomer_city.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_city.setText("a");

        Lcustomer_State.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lcustomer_State.setText("a");

        Lordered_cylinder.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lordered_cylinder.setText("a");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Amount:");

        Lamount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Lamount.setText("a");

        Lquantity.setText("jLabel17");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lstate, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addGap(229, 229, 229))
                            .addComponent(Lemail, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(Lnoofcylinders, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(Lcost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Laddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lcustomer_city, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lcustomer_State, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lordered_cylinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lcity, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(134, 134, 134)
                        .addComponent(Lpincode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(24, 24, 24)
                        .addComponent(Lcontact_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(Lcustomer_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(Lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Lquantity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Lnoofcylinders))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Lcost))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(Laddress, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcity)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lstate)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Lpincode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Lcontact_no))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Lcustomer_address, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcustomer_city)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Lcustomer_State))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Lordered_cylinder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Lamount))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Ordered_Cylinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Ordered_Cylinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Ordered_Cylinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Ordered_Cylinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Order_Cylinder().setVisible(true);
            }
        });
    }
   
    private String Temp;
    private String Order_id;
    private String Customer_Address;
    private String Customer_City;
    private String Customer_State;
    private String Supplier_Email;
    private String Customer_Email;
    private int Quantity;
    private String City;
    private String Address;
    private String State;
    private String No_of_Cylinder;
    private int Cost;
    private int Amount;
    private String Supplier_Name;
    private String pincode;
    private String Contact_no;
    private int Ordered_No_of_Cylinder;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Laddress;
    private javax.swing.JLabel Lamount;
    private javax.swing.JLabel Lcity;
    private javax.swing.JLabel Lcontact_no;
    private javax.swing.JLabel Lcost;
    private javax.swing.JLabel Lcustomer_State;
    private javax.swing.JLabel Lcustomer_address;
    private javax.swing.JLabel Lcustomer_city;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Lnoofcylinders;
    private javax.swing.JLabel Lordered_cylinder;
    private javax.swing.JLabel Lpincode;
    private javax.swing.JLabel Lquantity;
    private javax.swing.JLabel Lstate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
